<?php

defined('ABSPATH') || exit;

return [
    [
        'id'         => 1,
        'name'       => 'Дитячий плед',
        'price'      => 799,
        'old_price'  => 999,
        'badge'      => 'Хіт',
        'image'      => 'blanket.jpg',
        'rating'     => 4.9,
        'reviews'    => 124,
        'category'   => 'newborn',
        'brand'      => 'babyono',
        'age'        => '0-1',
        'popularity' => 95,
        'created_at' => '2026-07-10',
    ],
    [
        'id'         => 2,
        'name'       => 'М’яка іграшка',
        'price'      => 499,
        'old_price'  => 649,
        'badge'      => 'Акція',
        'image'      => 'toy.jpg',
        'rating'     => 4.8,
        'reviews'    => 86,
        'category'   => 'toys',
        'brand'      => 'fisher-price',
        'age'        => '1-3',
        'popularity' => 90,
        'created_at' => '2026-06-24',
    ],
    [
        'id'         => 3,
        'name'       => 'Боді для малюка',
        'price'      => 349,
        'old_price'  => null,
        'badge'      => 'Новинка',
        'image'      => 'bodysuit.jpg',
        'rating'     => 4.7,
        'reviews'    => 42,
        'category'   => 'clothes',
        'brand'      => 'chicco',
        'age'        => '0-1',
        'popularity' => 82,
        'created_at' => '2026-07-14',
    ],
    [
        'id'         => 4,
        'name'       => 'Прорізувач',
        'price'      => 199,
        'old_price'  => null,
        'badge'      => '',
        'image'      => 'teether.jpg',
        'rating'     => 4.9,
        'reviews'    => 68,
        'category'   => 'newborn',
        'brand'      => 'babyono',
        'age'        => '0-1',
        'popularity' => 88,
        'created_at' => '2026-05-18',
    ],
    [
        'id'         => 5,
        'name'       => 'Дитячі шкарпетки',
        'price'      => 149,
        'old_price'  => null,
        'badge'      => '',
        'image'      => 'socks.jpg',
        'rating'     => 4.6,
        'reviews'    => 31,
        'category'   => 'clothes',
        'brand'      => 'chicco',
        'age'        => '1-3',
        'popularity' => 70,
        'created_at' => '2026-04-12',
    ],
    [
        'id'         => 6,
        'name'       => 'Коробка для речей',
        'price'      => 599,
        'old_price'  => 749,
        'badge'      => '',
        'image'      => 'storage-box.jpg',
        'rating'     => 4.8,
        'reviews'    => 54,
        'category'   => 'newborn',
        'brand'      => 'babyono',
        'age'        => '0-1',
        'popularity' => 74,
        'created_at' => '2026-03-30',
    ],
    [
        'id'         => 7,
        'name'       => 'Подарунковий набір',
        'price'      => 1299,
        'old_price'  => 1599,
        'badge'      => 'Хіт',
        'image'      => 'gift-set.jpg',
        'rating'     => 5.0,
        'reviews'    => 97,
        'category'   => 'newborn',
        'brand'      => 'chicco',
        'age'        => '0-1',
        'popularity' => 98,
        'created_at' => '2026-06-29',
    ],
    [
        'id'         => 8,
        'name'       => 'Розвиваюча іграшка',
        'price'      => 699,
        'old_price'  => null,
        'badge'      => '',
        'image'      => 'educational-toy.jpg',
        'rating'     => 4.7,
        'reviews'    => 73,
        'category'   => 'toys',
        'brand'      => 'fisher-price',
        'age'        => '1-3',
        'popularity' => 85,
        'created_at' => '2026-05-07',
    ],
    [
        'id'         => 9,
        'name'       => 'Дитяча ковдра',
        'price'      => 899,
        'old_price'  => null,
        'badge'      => '',
        'image'      => 'blanket.jpg',
        'rating'     => 4.8,
        'reviews'    => 39,
        'category'   => 'newborn',
        'brand'      => 'babyono',
        'age'        => '0-1',
        'popularity' => 76,
        'created_at' => '2026-02-21',
    ],
    [
        'id'         => 10,
        'name'       => 'Пустушка',
        'price'      => 159,
        'old_price'  => null,
        'badge'      => '',
        'image'      => 'teether.jpg',
        'rating'     => 4.5,
        'reviews'    => 26,
        'category'   => 'newborn',
        'brand'      => 'chicco',
        'age'        => '0-1',
        'popularity' => 65,
        'created_at' => '2026-01-16',
    ],
    [
        'id'         => 11,
        'name'       => 'Дитячий комбінезон',
        'price'      => 1099,
        'old_price'  => null,
        'badge'      => 'Новинка',
        'image'      => 'bodysuit.jpg',
        'rating'     => 4.9,
        'reviews'    => 61,
        'category'   => 'clothes',
        'brand'      => 'chicco',
        'age'        => '1-3',
        'popularity' => 92,
        'created_at' => '2026-07-12',
    ],
    [
        'id'         => 12,
        'name'       => 'Ігровий килимок',
        'price'      => 1199,
        'old_price'  => null,
        'badge'      => '',
        'image'      => 'educational-toy.jpg',
        'rating'     => 4.8,
        'reviews'    => 48,
        'category'   => 'toys',
        'brand'      => 'fisher-price',
        'age'        => '0-1',
        'popularity' => 89,
        'created_at' => '2026-06-15',
    ],
];